name: Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
   test:
     name: Build and Test default scheme using iPhone 13 simulator
     runs-on: macos-latest
     strategy:
         matrix:
           destination: ['platform=iOS Simulator,OS=15.2,name=iPhone 13']
     steps:
       - name: Checkout
         uses: actions/checkout@v2
       - name: Build
         run: |
           xcodebuild clean build -project SwiftCafe.xcodeproj -scheme SwiftCafe -destination "${destination}"
         env: 
          destination: ${{ matrix.destination }}
       - name: Test
         run: |
           xcodebuild clean test -project SwiftCafe.xcodeproj -scheme SwiftCafe -destination "${destination}"
         env: 
          destination: ${{ matrix.destination }}
